apiVersion: v1
kind: Pod
metadata:
  name: crm-chat
  namespace: project-crm # This is the namespace we created
spec:
  containers:
  - name: web-api
    image: huycrouch/huyhq1010:v2
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
